# Generated by Django 6.1 on 2026-08-28 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° commande')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('CREEE', 'Créée'), ('ATTENTE_COMPTA', 'En attente Comptabilité'), ('ATTENTE_CONFORMITE', 'En attente Conformité'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='CREEE', max_length=20, verbose_name='Statut')),
                ('nom_prenoms', models.CharField(max_length=150, verbose_name='Nom et prénoms')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profession')),
                ('date_anniversaire', models.DateField(blank=True, null=True, verbose_name="Date d'anniversaire")),
                ('nom_facebook', models.CharField(blank=True, max_length=150, verbose_name="Nom d'utilisateur Facebook")),
                ('ordonnance_du_dr', models.CharField(blank=True, max_length=150, verbose_name='Ordonnance du Dr')),
                ('date_ordonnance', models.DateField(blank=True, null=True, verbose_name="Date de l'ordonnance")),
                ('od_sph', models.CharField(blank=True, max_length=20, verbose_name='OD - SPH')),
                ('od_cyl', models.CharField(blank=True, max_length=20, verbose_name='OD - CYL')),
                ('od_axe', models.CharField(blank=True, max_length=20, verbose_name='OD - AXE')),
                ('od_add', models.CharField(blank=True, max_length=20, verbose_name='OD - ADD')),
                ('od_vp', models.CharField(blank=True, max_length=20, verbose_name='OD - VP')),
                ('od_hvp', models.CharField(blank=True, max_length=20, verbose_name='OD - HVP')),
                ('od_eg', models.CharField(blank=True, max_length=20, verbose_name='OD - EG')),
                ('od_ed', models.CharField(blank=True, max_length=20, verbose_name='OD - ED')),
                ('og_sph', models.CharField(blank=True, max_length=20, verbose_name='OG - SPH')),
                ('og_cyl', models.CharField(blank=True, max_length=20, verbose_name='OG - CYL')),
                ('og_axe', models.CharField(blank=True, max_length=20, verbose_name='OG - AXE')),
                ('og_add', models.CharField(blank=True, max_length=20, verbose_name='OG - ADD')),
                ('og_vp', models.CharField(blank=True, max_length=20, verbose_name='OG - VP')),
                ('og_hvp', models.CharField(blank=True, max_length=20, verbose_name='OG - HVP')),
                ('og_eg', models.CharField(blank=True, max_length=20, verbose_name='OG - EG')),
                ('og_ed', models.CharField(blank=True, max_length=20, verbose_name='OG - ED')),
                ('monture', models.CharField(blank=True, max_length=150, verbose_name='Monture')),
                ('verres', models.CharField(blank=True, max_length=150, verbose_name='Verres')),
                ('divers_accessoires', models.CharField(blank=True, max_length=255, verbose_name='Divers / accessoires')),
                ('offre_2eme_paire_monture', models.CharField(blank=True, max_length=150, verbose_name='Offre 2e paire monture')),
                ('montant_total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Montant total')),
                ('acompte', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Acompte')),
                ('pec_assurance', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prise en charge (PEC)')),
                ('assurance_client', models.BooleanField(default=False, verbose_name='Client assuré')),
                ('nom_assurance', models.CharField(blank=True, max_length=150, verbose_name="Nom de l'assurance")),
                ('justificatif_assurance', models.FileField(blank=True, null=True, upload_to='justificatifs/', verbose_name="Justificatif d'assurance")),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date de livraison')),
                ('commande_soldee_le', models.DateField(blank=True, null=True, verbose_name='Commande soldée le')),
                ('date_validation_comptabilite', models.DateTimeField(blank=True, null=True)),
                ('date_validation_conformite', models.DateTimeField(blank=True, null=True)),
                ('commentaire_comptabilite', models.TextField(blank=True, verbose_name='Commentaire Comptabilité')),
                ('commentaire_conformite', models.TextField(blank=True, verbose_name='Commentaire Conformité')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('valide_comptabilite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees_comptabilite', to=settings.AUTH_USER_MODEL, verbose_name='Validée par (Comptabilité)')),
                ('valide_conformite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees_conformite', to=settings.AUTH_USER_MODEL, verbose_name='Validée par (Conformité)')),
            ],
            options={
                'verbose_name': 'Fiche de commande',
                'verbose_name_plural': 'Fiches de commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='Action')),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='fiches.fichecommande')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de fiche',
                'verbose_name_plural': 'Historiques de fiches',
                'ordering': ['-date_action'],
            },
        ),
    ]
