# Generated by Django 4.2.30 on 2026-09-04 17:21

import django.core.validators
from django.db import migrations, models
import fiches.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichecommande',
            name='justificatif_assurance',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), fiches.models.validate_justificatif_assurance], verbose_name="Justificatif d'assurance"),
        ),
    ]
